# .github/workflows/optimize.yml

name: Optimize
on: [workflow_dispatch]

# This Workflow is triggered through the GitHub API:
#   curl -X POST \
#        -H "Authorization: Bearer <token>" \
#        -d '{"ref":"main"}' \
#        https://api.github.com/repos/<owner>/<repo>/actions/workflows/optimize.yml/dispatches
#
# Replacing <token> by a personal access token with scope `public_repo`, <owner>
# by the repositories owner (user or organization), <repo> by the repositories
# name.
#
# NOTE: "main" in the payload (-d) refers to the branch on which the workflow
# should be triggered. Usually you want this to be the default branch.
#
# NOTE: "optimize.yml" in the URL has to be updated if the workflow file is not
# called "optimize.yml".

# The minimum required permissions
permissions:
  contents: write

jobs:
  svgs:
    name: SVGs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Optimize SVGs
      uses: ericcornelissen/svgo-action@v3
      id: svgo
    - name: Commit optimizations
      uses: stefanzweifel/git-auto-commit-action@v4
      if: ${{steps.svgo.outputs.DID_OPTIMIZE}}
      with:
        commit_message: Optimize ${{steps.svgo.outputs.OPTIMIZED_COUNT}} SVG(s)
